version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/usr/src/app/data/walkthrough.db
      - BACKUP_PATH=/usr/src/app/data/backups
      - npm_config_build_from_source=true
    volumes:
      - ./data:/usr/src/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  walkthrough_data:
    driver: local 